# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('birth_year', models.DateField()),
                ('bio', models.TextField()),
                ('avatar_link', models.URLField()),
            ],
        ),
    ]
