# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
