# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171023_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar_link',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
